In [3]:
import sys
import os
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))
from config import DATA_DIR
from data.loaders.raw_loader import RawEEGLoader
import numpy as np
import mne

os.environ['KMP_DUPLICATE_LIB_OK']='True' # To prevent the kernel from dying.


eeg_path = DATA_DIR / "Sub02" / "daniel_1_eeg.vhdr"
raw = mne.io.read_raw_brainvision(eeg_path, preload=True, verbose=False)

# Check events (from annotations for BrainVision files)
events, event_id = mne.events_from_annotations(raw, verbose=True)

print("Event ID mapping:")
print(event_id)
print("\nFirst 20 events:")
print(events[:20])
print(f"\nTotal events: {len(events)}")
print(f"Unique sample indices: {len(np.unique(events[:, 0]))} / {len(events)}")

# Check for duplicates
sample_indices = events[:, 0]
unique, counts = np.unique(sample_indices, return_counts=True)
duplicates = unique[counts > 1]
if len(duplicates) > 0:
    print(f"\nDuplicate sample indices found: {len(duplicates)}")
    for dup in duplicates[:5]:  # Show first 5
        print(f"  Sample {dup}: {events[events[:, 0] == dup]}")

Used Annotations descriptions: [np.str_('Response/R  4'), np.str_('Response/R 15'), np.str_('Stimulus/S  1'), np.str_('Stimulus/S  2'), np.str_('Stimulus/S  3'), np.str_('Stimulus/S  5'), np.str_('Stimulus/S 14'), np.str_('Stimulus/S 15')]
Event ID mapping:
{np.str_('Response/R  4'): 1004, np.str_('Response/R 15'): 1015, np.str_('Stimulus/S  1'): 1, np.str_('Stimulus/S  2'): 2, np.str_('Stimulus/S  3'): 3, np.str_('Stimulus/S  5'): 5, np.str_('Stimulus/S 14'): 14, np.str_('Stimulus/S 15'): 15}

First 20 events:
[[ 83470      0   1004]
 [102564      0      1]
 [102564      0   1004]
 [106409      0      2]
 [138484      0      5]
 [145158      0      1]
 [148756      0      2]
 [180825      0      5]
 [186571      0      1]
 [190320      0      2]
 [222327      0      5]
 [229802      0      1]
 [233752      0      2]
 [265812      0      5]
 [271666      0      1]
 [275749      0      2]
 [307754      0      5]
 [313414      0      1]
 [316796      0      2]
 [348802      0      5]]

T

In [2]:
import sys
import os
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))
from config import DATA_DIR
from data.loaders.raw_loader import RawEEGLoader

os.environ['KMP_DUPLICATE_LIB_OK']='True' # To prevent the kernel from dying.

# Create loader with default config
loader = RawEEGLoader()

# Load raw EEG file
data = loader.load(
      eeg_path= DATA_DIR / "Sub02" / "daniel_1_eeg.vhdr",
      participant_id="sub-002"
  )

NOTE: pick_types() is a legacy function. New code should use inst.pick(...).


RuntimeError: Event time samples were not unique. Consider setting the `event_repeated` parameter."